/*
 * Copyright (c) 2020  Thiago Lopes da Silva
 * All Rights Reserved.
 *
 */

// This code was generated by NGlauber (https://github.com/nglauber/books_jetpack/blob/master/presentation/src/main/java/dominando/android/presentation/ViewState.kt)

package com.example.presentation.model

class ViewState<D>(
    val status: Status,
    val data: D? = null,
    val error: Throwable? = null
) {
    enum class Status {
        LOADING, SUCCESS, ERROR
    }
}